const d=dashboardData,$=s=>document.querySelector(s),fmt=n=>Number.isFinite(n)?(Math.round(n*10)/10).toFixed(1):"–",clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const actualAt=(p,i)=>p.actual?.[i]??null, selectedMonth=()=>Number($("#monthSelect").value), available=i=>d.projects.filter(p=>actualAt(p,i)!==null);
const avg=i=>{const ps=available(i);return ps.length?ps.reduce((s,p)=>s+actualAt(p,i),0)/ps.length:null};
const status=(p,i)=>actualAt(p,i)>=100?{key:"done",label:"แล้วเสร็จ"}:{key:"ongoing",label:"อยู่ระหว่างดำเนินการ"};
d.months.forEach((m,i)=>{const o=document.createElement("option");o.value=i;o.textContent=m;$("#monthSelect").appendChild(o)});$("#monthSelect").value=d.meta.latestMonthIndex;$("#footerSource").textContent=`แหล่งข้อมูล: ${d.meta.source}`;
let actualChart,statusChart;function charts(i){const labels=d.months.slice(0,i+1),vals=labels.map((_,x)=>avg(x));actualChart?.destroy();actualChart=new Chart($("#actualChart"),{type:"line",data:{labels,datasets:[{label:"ความก้าวหน้าเฉลี่ย (%)",data:vals,borderColor:"#2f80c9",backgroundColor:"#2f80c916",fill:true,pointRadius:3,tension:.25}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},scales:{y:{min:0,max:100,ticks:{callback:v=>v+"%"}}}}});const ps=available(i),done=ps.filter(p=>actualAt(p,i)>=100).length,ongoing=ps.length-done;statusChart?.destroy();statusChart=new Chart($("#statusChart"),{type:"doughnut",data:{labels:["แล้วเสร็จ","อยู่ระหว่างดำเนินการ"],datasets:[{data:[done,ongoing],backgroundColor:["#2f80c9","#c84444"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:"68%",plugins:{legend:{display:false}}}})}
function kpis(i){const ps=available(i),done=ps.filter(p=>actualAt(p,i)>=100).length;$("#kpiTotal").textContent=ps.length;$("#kpiDone").textContent=done;$("#kpiOngoing").textContent=ps.length-done;$("#kpiActual").textContent=fmt(avg(i));$("#subtitle").textContent=`ปีงบประมาณ ${d.meta.fiscalYear} · เดือนรายงาน ${d.months[i]}`;$("#chartMonthChip").textContent=d.months[i]}
function rows(p,sel){return d.months.map((m,i)=>{const a=actualAt(p,i);if(a===null&&i>sel)return"";return `<tr class="${i===sel?'selected':''}"><td>${m}</td><td>${a===null?'–':fmt(a)+'%'}</td></tr>`}).join("")}
function projects(i){const q=$("#searchInput").value.trim().toLowerCase(),f=$("#statusFilter").value;const html=d.projects.map(p=>{const a=actualAt(p,i);if(a===null)return null;const s=status(p,i);if(q&&!(p.name+" "+p.unit).toLowerCase().includes(q))return null;if(f&&s.key!==f)return null;return `<article class="project-item"><div class="project-summary" style="grid-template-columns:1fr 120px 180px 32px" role="button" tabindex="0" aria-expanded="false"><div><div class="project-name">${p.id}. ${p.name}</div><span class="unit">${p.unit} · สถานะข้อมูล: ${p.officialStatus}</span></div><div class="metric">${fmt(a)}%</div><div class="traffic ${s.key==='done'?'green':'red'}">${s.label}</div><div class="chev">⌄</div></div><div class="project-detail"><div class="detail-grid"><div class="detail-meta"><h3>ข้อมูลโครงการ</h3><p><b>ตัวชี้วัด:</b> ${p.indicator}</p><p><b>เดือนที่เลือก:</b> ${d.months[i]}</p><p><b>ผลล่าสุด:</b> ${fmt(a)}%</p><div class="progress-track"><i style="width:${clamp(a,0,100)}%"></i></div></div><div><table class="monthly-table"><thead><tr><th>เดือน</th><th>ผลความก้าวหน้า</th></tr></thead><tbody>${rows(p,i)}</tbody></table></div></div></div></article>`}).filter(Boolean).join("");$("#projectList").innerHTML=html||'<div style="padding:24px;color:#748078;text-align:center">ไม่พบโครงการตามตัวกรอง</div>';document.querySelectorAll(".project-summary").forEach(el=>{const t=()=>{const item=el.closest(".project-item"),open=item.classList.toggle("open");el.setAttribute("aria-expanded",open)};el.onclick=t;el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();t()}}})}
function render(){const i=selectedMonth();kpis(i);charts(i);projects(i)}$("#monthSelect").onchange=render;$("#searchInput").oninput=()=>projects(selectedMonth());$("#statusFilter").onchange=()=>projects(selectedMonth());render();
